# Generated by Django 5.2.17 on 2026-08-14 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_camera_permission_user_location_permission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('pin_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('place_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('tagged_at', models.DateTimeField()),
                ('text_note', models.CharField(blank=True, max_length=500, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('included_in_segment', models.BooleanField(default=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='accounts.user')),
            ],
            options={
                'db_table': 'pin',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('source_type', models.CharField(choices=[('captured', '촬영'), ('uploaded', '업로드')], default='uploaded', max_length=30)),
                ('photo_url', models.CharField(max_length=500)),
                ('is_main', models.BooleanField(default=False)),
                ('pin', models.ForeignKey(db_column='pin_id', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='travel.pin')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
        migrations.CreateModel(
            name='TravelSegment',
            fields=[
                ('segment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('cover_photo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='travel_segments', to='accounts.user')),
            ],
            options={
                'db_table': 'travel_segment',
            },
        ),
        migrations.AddField(
            model_name='pin',
            name='segment',
            field=models.ForeignKey(blank=True, db_column='segment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pins', to='travel.travelsegment'),
        ),
        migrations.CreateModel(
            name='VoiceMemo',
            fields=[
                ('voice_memo_id', models.AutoField(primary_key=True, serialize=False)),
                ('audio_url', models.CharField(max_length=255)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('pin', models.OneToOneField(db_column='pin_id', on_delete=django.db.models.deletion.CASCADE, related_name='voicememo', to='travel.pin')),
            ],
            options={
                'db_table': 'voice_memo',
            },
        ),
        migrations.CreateModel(
            name='CountryStamp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=10)),
                ('country_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='country_stamps', to='accounts.user')),
            ],
            options={
                'db_table': 'country_stamp',
                'unique_together': {('user', 'country_code')},
            },
        ),
    ]
