# Generated by Django 5.2.17 on 2026-08-14 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='segment',
            field=models.ForeignKey(blank=True, db_column='segment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='travel.travelsegment'),
        ),
    ]
