# Generated by Django 5.2.17 on 2026-08-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_pin_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicememo',
            name='duration_sec',
            field=models.IntegerField(default=0),
        ),
    ]
