# Generated by Django 6.1 on 2026-08-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_pin_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
