# Generated by Django 6.1 on 2026-08-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_pin_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='measured_brightness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='measured_density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='measured_photo_type',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='measured_tone',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='measured_vividness',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
