# Generated by Django 6.0.7 on 2026-08-14 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='onboarding_progress', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('current_stage', models.CharField(choices=[('BASIC_QUESTION', '기본 질문'), ('AB_SELECTION', 'A/B 선택'), ('MOODBOARD', '무드보드'), ('COMPLETED', '완료')], default='BASIC_QUESTION', max_length=20)),
                ('current_round', models.PositiveSmallIntegerField(default=1)),
                ('is_retrain', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TasteProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='taste_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('taste', models.TextField(blank=True, default='')),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileRetrainHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_retrain_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BasicQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveSmallIntegerField()),
                ('answer', models.CharField(max_length=100)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_question_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'round_no')},
            },
        ),
        migrations.CreateModel(
            name='SelectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveSmallIntegerField()),
                ('photo_id', models.PositiveIntegerField()),
                ('status', models.BooleanField()),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'round_no', 'photo_id')},
            },
        ),
        migrations.CreateModel(
            name='TasteProfileAxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis_code', models.CharField(choices=[('brightness', '밝기'), ('vividness', '채도'), ('tone', '색온도'), ('density', '구도와 밀도'), ('photo_type', '사진종류')], max_length=50)),
                ('value', models.IntegerField()),
                ('status', models.CharField(choices=[('REFLECTED', '반영 완료'), ('PENDING', '미반영')], default='PENDING', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taste_axes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'axis_code')},
            },
        ),
    ]
