# Generated by Django 6.0.7 on 2026-08-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasteprofileaxis',
            name='axis_code',
            field=models.CharField(choices=[('brightness', '밝기'), ('vividness', '채도'), ('tone', '색온도'), ('density', '구도와 밀도'), ('photo_type', '사진종류')], max_length=50),
        ),
    ]
