# Generated by Django 6.0.7 on 2026-08-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taste', '0002_alter_tasteprofileaxis_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileretrainhistory',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
