# Generated by Django 6.1 on 2026-08-15 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_display_name_remove_user_google_id_and_more'),
        ('taste', '0003_alter_profileretrainhistory_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicquestionresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_question_responses', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='onboarding_progress', serialize=False, to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='profileretrainhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_retrain_history', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='selectionphoto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_photos', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='tasteprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='taste_profile', serialize=False, to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='tasteprofileaxis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taste_axes', to='accounts.user'),
        ),
    ]
