# Generated by Django 6.0.7 on 2026-08-12 06:09

import secrets

import django.db.models.deletion
from django.db import migrations, models


def _generate_session_token() -> str:
    return secrets.token_urlsafe(32)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('google_id', models.CharField(help_text='구글 OAuth id_token의 sub 값. 로그인 시 이 값으로 계정 조회/생성', max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('display_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('permission_intro_shown', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(default=_generate_session_token, editable=False, max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.user')),
            ],
            options={
                'db_table': 'session',
                'indexes': [models.Index(fields=['token'], name='session_token_9105e5_idx')],
            },
        ),
    ]
