# Generated by Django 5.2.17 on 2026-08-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='camera_permission',
            field=models.CharField(blank=True, choices=[('granted', '허용'), ('denied', '거부'), ('unsupported', '미지원')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location_permission',
            field=models.CharField(blank=True, choices=[('granted', '허용'), ('denied', '거부'), ('unsupported', '미지원')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='microphone_permission',
            field=models.CharField(blank=True, choices=[('granted', '허용'), ('denied', '거부'), ('unsupported', '미지원')], max_length=20, null=True),
        ),
    ]
