# Generated by Django 5.2.17 on 2026-08-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_camera_permission_user_location_permission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_at',
        ),
        migrations.AddField(
            model_name='user',
            name='account_identifier',
            field=models.CharField(default='', help_text='구글 ID 토큰의 sub 값. 로그인 시 이 값으로 계정 조회/생성', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
