# Generated by Django 5.2.17 on 2026-08-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_display_name_remove_user_google_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_trip_name_override',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
