# Generated by Django 6.1 on 2026-08-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_current_trip_name_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
