# Generated by Django 6.0.7 on 2026-08-12 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfcTag',
            fields=[
                ('tag_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_type', models.CharField(choices=[('bag', '가방'), ('charm', '참'), ('keyring', '키링')], max_length=20)),
                ('product_name', models.CharField(max_length=100)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='nfc_tags', to='accounts.user')),
            ],
            options={
                'db_table': 'nfc_tag',
            },
        ),
    ]
