# Generated by Django 6.0.7 on 2026-08-13 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_session'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfctag',
            name='tag_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nfctag',
            name='unlinked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nfctag',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_tags', to='accounts.user'),
        ),
    ]
