# Generated by Django 5.2.17 on 2026-08-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_nfctag_tag_count_nfctag_unlinked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfctag',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nfctag',
            name='product_type',
            field=models.CharField(choices=[('bag', '가방'), ('charm', '참'), ('keyring', '키링'), ('unknown', '미확인')], max_length=20),
        ),
    ]
